### PR TITLE
Site toggle

### LINKED ISSUE #5: Add a site toggle to enable/disable
We've had a request to add this to one of our instances of Omeka S that supports library digital exhibits, but we would like for the feature to only affect sites that elect to use it.

I implemented this behavior through a toggle button in the site admin if you are willing to entertain a pull request.

### PR DESCRIPTION
**Pull request by alexdryden**
Creates a toggle in site admin that lets users enable the feature on a site-by-site basis. Fixes #5.

### CODE REVIEW

**Comment by zerocrates** [comment]
My major concern here is that this is going to mean people upgrading will have all their embeds turned off and have to turn them back on site by site. Simplest way to avoid that issue is to make the switch default to enabled for each site (or change it to a *dis*able switch. This would have to be done both in the form and as a default passed when getting the setting in the actual renderer.

My second point would be: rather than having a copy of the ThumbnailRenderer's code in the "don't embed" path, you should just create an use an instance of the thumbnail renderer.

**Comment by alexdryden** [comment]
Thanks, @zerocrates! I forget what I was thinking when I just copied the ThumbnailRenderer, but you are absolutely right on both counts. Switched to a "disable" button because the default behavior probably should be to do what the module says and have the optional behavior be to disable it.

**Comment by zerocrates** [comment]
One minor further note: the getLinkUrl function in the renderer came along with your thumbnail renderer copy, so it's no longer needed.

**Comment by alexdryden** [comment]
Whoops, thanks!

**Comment by zerocrates** [comment]
Oh, one thing I didn't consider: have you checked this on the admin? I think you might have a problem where you're reading the site settings always, even if you're not in a site.

**Comment by alexdryden** [comment]
Oh, great point. Yeah, it would try to check on admin pages.

**Pull request merged**
